trigger:
- main  # Replace 'main' with your default branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip
    python3 --version
  displayName: 'Install Python'

- script: |
    python3 myapp.py
  displayName: 'Run myapp.py'

