trigger:
- main  # Replace with your default branch if different

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@1
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python myapp.py
  displayName: 'Run Python myapp.py Script'
